-- ===============================================
-- 데이터 삽입 SQL 모음 파일
-- 작성일: 2025-08-21
-- 설명: 프로젝트에서 사용할 모든 기본 데이터 삽입 SQL 스크립트
-- ===============================================

-- =============================================
-- TechStack 데이터 삽입
-- =============================================

-- 기존 TechStack 데이터 삭제 (필요시 주석 해제)
-- DELETE FROM tech_stack;

-- TechStack 데이터 삽입
INSERT INTO tech_stack (name) VALUES 
-- Frontend 기술
('React'),
('Vue.js'),
('Angular'),
('Next.js'),
('Nuxt.js'),
('Svelte'),
('SvelteKit'),
('JavaScript'),
('TypeScript'),
('HTML5'),
('CSS3'),
('SCSS'),
('Sass'),
('Less'),
('Styled Components'),
('Emotion'),
('Tailwind CSS'),
('Bootstrap'),
('Material-UI'),
('Ant Design'),
('Chakra UI'),
('Webpack'),
('Vite'),
('Parcel'),
('Rollup'),
('ESLint'),
('Prettier'),
('Jest'),
('Cypress'),
('Playwright'),
('React Testing Library'),
('Storybook'),

-- Backend 기술
('Spring Boot'),
('Spring Framework'),
('Spring Security'),
('Spring Data JPA'),
('Spring Cloud'),
('Node.js'),
('Express.js'),
('Nest.js'),
('Fastify'),
('Django'),
('Flask'),
('FastAPI'),
('ASP.NET Core'),
('ASP.NET'),
('Laravel'),
('Symfony'),
('CodeIgniter'),
('Ruby on Rails'),
('Sinatra'),
('Phoenix'),
('Gin'),
('Echo'),
('Fiber'),
('Actix Web'),
('Rocket'),
('Ktor'),
('Quarkus'),
('Micronaut'),
('Helidon'),

-- 프로그래밍 언어
('Java'),
('Python'),
('JavaScript'),
('TypeScript'),
('C#'),
('C++'),
('C'),
('Go'),
('Rust'),
('Kotlin'),
('Scala'),
('Clojure'),
('Ruby'),
('PHP'),
('Swift'),
('Objective-C'),
('Dart'),
('R'),
('MATLAB'),
('Perl'),
('Haskell'),
('Elixir'),
('Erlang'),
('F#'),
('VB.NET'),
('COBOL'),
('Fortran'),
('Assembly'),
('Bash'),
('PowerShell'),

-- 데이터베이스
('PostgreSQL'),
('MySQL'),
('MariaDB'),
('SQLite'),
('Oracle Database'),
('SQL Server'),
('MongoDB'),
('Redis'),
('Elasticsearch'),
('Cassandra'),
('DynamoDB'),
('CouchDB'),
('Neo4j'),
('InfluxDB'),
('TimescaleDB'),
('Firebase Firestore'),
('Supabase'),
('PlanetScale'),
('Neon'),
('CockroachDB'),
('Amazon RDS'),
('Amazon Aurora'),
('Google Cloud SQL'),
('Azure SQL Database'),

-- Cloud & DevOps
('AWS'),
('AWS EC2'),
('AWS S3'),
('AWS RDS'),
('AWS Lambda'),
('AWS ECS'),
('AWS EKS'),
('AWS CloudFormation'),
('AWS CDK'),
('AWS API Gateway'),
('AWS CloudFront'),
('AWS Route 53'),
('AWS VPC'),
('AWS IAM'),
('AWS SQS'),
('AWS SNS'),
('AWS EventBridge'),
('Amazon ElastiCache'),
('Amazon OpenSearch'),
('Google Cloud Platform'),
('Google Cloud Run'),
('Google Cloud Functions'),
('Google Kubernetes Engine'),
('Google Cloud Storage'),
('Google BigQuery'),
('Google Cloud SQL'),
('Firebase'),
('Azure'),
('Azure App Service'),
('Azure Functions'),
('Azure Kubernetes Service'),
('Azure SQL Database'),
('Azure Cosmos DB'),
('Azure Storage'),
('Docker'),
('Kubernetes'),
('Helm'),
('Terraform'),
('Ansible'),
('Chef'),
('Puppet'),
('Vagrant'),
('Jenkins'),
('GitLab CI/CD'),
('GitHub Actions'),
('Azure DevOps'),
('CircleCI'),
('Travis CI'),
('Bitbucket Pipelines'),
('ArgoCD'),
('Flux'),
('Prometheus'),
('Grafana'),
('ELK Stack'),
('Fluentd'),
('Logstash'),
('Kibana'),
('Jaeger'),
('Zipkin'),
('New Relic'),
('Datadog'),
('Sentry'),
('Consul'),
('Vault'),
('Nomad'),
('Istio'),
('Envoy'),
('NGINX'),
('Apache HTTP Server'),
('Traefik'),
('HAProxy'),
('Cloudflare'),

-- Mobile Development
('React Native'),
('Flutter'),
('Ionic'),
('Xamarin'),
('Cordova'),
('SwiftUI'),
('UIKit'),
('Android SDK'),
('Kotlin Multiplatform'),
('Unity'),
('Unreal Engine'),

-- AI/ML & Data Science
('TensorFlow'),
('PyTorch'),
('Keras'),
('Scikit-learn'),
('Pandas'),
('NumPy'),
('Matplotlib'),
('Seaborn'),
('Plotly'),
('Jupyter'),
('Anaconda'),
('Apache Spark'),
('Apache Kafka'),
('Apache Airflow'),
('MLflow'),
('Kubeflow'),
('ONNX'),
('OpenCV'),
('Hugging Face'),
('LangChain'),
('OpenAI API'),
('Anthropic Claude'),
('Cohere'),

-- Testing & Quality
('JUnit'),
('TestNG'),
('Mockito'),
('Selenium'),
('Cucumber'),
('Postman'),
('Insomnia'),
('k6'),
('Artillery'),
('Apache JMeter'),
('SonarQube'),
('ESLint'),
('Prettier'),
('Checkstyle'),
('SpotBugs'),
('PMD'),

-- Version Control & Collaboration
('Git'),
('GitHub'),
('GitLab'),
('Bitbucket'),
('Azure Repos'),
('SVN'),
('Mercurial'),
('Jira'),
('Confluence'),
('Slack'),
('Microsoft Teams'),
('Discord'),
('Notion'),
('Trello'),
('Asana'),
('Linear'),
('Monday.com'),

-- Design & UI/UX
('Figma'),
('Adobe XD'),
('Sketch'),
('InVision'),
('Zeplin'),
('Adobe Photoshop'),
('Adobe Illustrator'),
('Canva'),
('Framer'),
('Principle'),

-- Development Tools & IDEs
('Visual Studio Code'),
('IntelliJ IDEA'),
('Eclipse'),
('NetBeans'),
('Xcode'),
('Android Studio'),
('PyCharm'),
('WebStorm'),
('PhpStorm'),
('RubyMine'),
('GoLand'),
('CLion'),
('DataGrip'),
('Rider'),
('Visual Studio'),
('Vim'),
('Emacs'),
('Sublime Text'),
('Atom'),
('Brackets'),

-- Web Technologies
('GraphQL'),
('REST API'),
('gRPC'),
('WebSocket'),
('Socket.io'),
('OAuth 2.0'),
('JWT'),
('OpenAPI'),
('Swagger'),
('Progressive Web App'),
('Service Worker'),
('WebAssembly'),
('WebRTC'),

-- Game Development
('Unity 3D'),
('Unreal Engine 4'),
('Unreal Engine 5'),
('Godot'),
('GameMaker Studio'),
('Construct 3'),
('Phaser'),
('Three.js'),
('Babylon.js'),
('OpenGL'),
('DirectX'),
('Vulkan'),

-- Blockchain & Web3
('Ethereum'),
('Solidity'),
('Web3.js'),
('Ethers.js'),
('Hardhat'),
('Truffle'),
('Polygon'),
('Binance Smart Chain'),
('Solana'),
('Cardano'),
('Polkadot'),
('Hyperledger'),
('IPFS'),

-- IoT & Embedded
('Arduino'),
('Raspberry Pi'),
('ESP32'),
('ESP8266'),
('STM32'),
('FreeRTOS'),
('Zephyr'),
('Mbed'),
('PlatformIO'),
('MQTT'),
('CoAP'),
('LoRaWAN'),

-- Security
('OWASP'),
('Burp Suite'),
('Metasploit'),
('Nmap'),
('Wireshark'),
('Kali Linux'),
('Penetration Testing'),
('Ethical Hacking'),
('SSL/TLS'),
('PKI'),
('OAuth'),
('SAML'),
('LDAP'),
('Active Directory'),

-- Virtualization & Containers
('VMware'),
('VirtualBox'),
('QEMU'),
('Proxmox'),
('Hyper-V'),
('Docker Compose'),
('Docker Swarm'),
('Podman'),
('LXC'),
('OpenShift'),
('Rancher'),

-- Monitoring & Observability
('Nagios'),
('Zabbix'),
('Cacti'),
('PRTG'),
('SolarWinds'),
('Splunk'),
('Elastic APM'),
('Application Insights'),
('CloudWatch'),
('Stackdriver'),

-- Networking
('TCP/IP'),
('HTTP/HTTPS'),
('DNS'),
('BGP'),
('OSPF'),
('VLAN'),
('VPN'),
('SDN'),
('OpenFlow'),
('Cisco'),
('Juniper'),
('Palo Alto'),
('Fortinet'),

-- Business Intelligence
('Tableau'),
('Power BI'),
('QlikView'),
('Looker'),
('Metabase'),
('Apache Superset'),
('D3.js'),
('Chart.js'),
('Highcharts'),
('Google Analytics'),
('Adobe Analytics'),

-- CMS & E-commerce
('WordPress'),
('Drupal'),
('Joomla'),
('Magento'),
('Shopify'),
('WooCommerce'),
('PrestaShop'),
('OpenCart'),
('BigCommerce'),
('Strapi'),
('Contentful'),
('Sanity'),
('Ghost'),
('Headless CMS'),

-- Message Queues & Event Streaming
('RabbitMQ'),
('Apache ActiveMQ'),
('Amazon SQS'),
('Google Pub/Sub'),
('Azure Service Bus'),
('NATS'),
('ZeroMQ'),
('Pulsar')

ON CONFLICT (name) DO NOTHING;

-- =============================================
-- 추가 데이터 삽입 섹션
-- (향후 다른 테이블들의 데이터 삽입 SQL이 여기에 추가됩니다)
-- =============================================

-- 삽입된 데이터 개수 확인
SELECT COUNT(*) as total_tech_stacks FROM tech_stack;

-- =============================================
-- 프로젝트 데이터 삽입 섹션
-- =============================================

-- 프로젝트 모집 게시글 샘플 데이터 (TestDataInitializer에서 자동 생성됨)
-- 참고: 프로젝트 데이터는 Java 코드에서 동적으로 생성되며,
-- 사용자, TechPart, TechStack과의 관계를 자동으로 설정합니다.

-- 프로젝트 관련 테이블들:
-- - project_recruitment: 프로젝트 모집 게시글
-- - project_tech_part: 프로젝트-기술파트 연결
-- - project_tech_stack: 프로젝트-기술스택 연결
-- - project_member: 프로젝트 멤버
-- - project_application: 프로젝트 지원
-- - project_comment: 프로젝트 댓글

-- 프로젝트 모집 게시글 데이터 삽입 (샘플 30개)
INSERT INTO project_recruitment (team_leader_id, title, description, recruit_deadline, start_date, end_date, status, view_count, recruit_count, created_at, updated_at) VALUES 
(2, 'AI 기반 개인 맞춤형 학습 플랫폼 개발', '개인의 학습 패턴을 분석하여 최적화된 학습 경로를 제공하는 AI 플랫폼입니다.', '2025-09-15', '2025-09-20', '2025-12-20', 'RECRUITING', 45, 5, NOW(), NOW()),
(3, '실시간 협업 화이트보드 웹 애플리케이션', '실시간으로 여러 사용자가 함께 협업할 수 있는 디지털 화이트보드를 구현합니다.', '2025-09-20', '2025-09-25', '2025-11-25', 'RECRUITING', 67, 4, NOW(), NOW()),
(5, '블록체인 기반 탈중앙화 소셜 미디어', '사용자의 프라이버시를 보장하면서 탈중앙화된 소셜 네트워킹을 제공합니다.', '2025-09-10', '2025-09-15', '2026-01-15', 'IN_PROGRESS', 89, 6, NOW(), NOW()),
(8, 'IoT 스마트 홈 자동화 시스템', 'IoT 센서와 AI를 활용하여 스마트 홈 환경을 자동으로 제어하는 시스템입니다.', '2025-10-01', '2025-10-05', '2026-02-05', 'RECRUITING', 123, 7, NOW(), NOW()),
(12, '머신러닝을 활용한 주식 투자 분석 도구', '딥러닝 알고리즘을 사용하여 주식 시장 동향을 예측하고 투자 전략을 제안합니다.', '2025-09-25', '2025-10-01', '2026-01-01', 'RECRUITING', 234, 4, NOW(), NOW()),
(15, '모바일 AR 쇼핑 경험 애플리케이션', 'AR 기술을 활용하여 실제 공간에서 가상 제품을 체험할 수 있는 쇼핑 앱입니다.', '2025-09-18', '2025-09-23', '2025-12-23', 'RECRUITING', 156, 5, NOW(), NOW()),
(20, '클라우드 기반 팀 프로젝트 관리 도구', '팀 프로젝트의 전 과정을 효율적으로 관리할 수 있는 클라우드 기반 도구입니다.', '2025-09-22', '2025-09-28', '2025-12-28', 'RECRUITING', 78, 6, NOW(), NOW()),
(25, '실시간 언어 번역 화상 회의 서비스', '실시간 언어 번역 기능이 포함된 화상 회의 솔루션을 개발합니다.', '2025-09-30', '2025-10-05', '2026-01-05', 'RECRUITING', 345, 8, NOW(), NOW()),
(30, '게임화된 온라인 코딩 교육 플랫폼', '게임 요소를 접목하여 재미있게 프로그래밍을 학습할 수 있는 교육 플랫폼입니다.', '2025-09-12', '2025-09-18', '2025-11-18', 'COMPLETED', 267, 3, NOW(), NOW()),
(35, '환경 데이터 모니터링 및 분석 시스템', '환경 센서 데이터를 수집하고 분석하여 환경 변화를 모니터링하는 시스템입니다.', '2025-10-05', '2025-10-10', '2026-02-10', 'RECRUITING', 189, 5, NOW(), NOW()),
(40, 'NFT 기반 디지털 아트 마켓플레이스', 'NFT 기술을 활용한 디지털 아트 작품 거래 및 전시 플랫폼을 구축합니다.', '2025-09-14', '2025-09-20', '2025-12-20', 'RECRUITING', 445, 7, NOW(), NOW()),
(45, '음성 인식 기반 AI 비서 앱', '자연어 처리 기술을 활용한 스마트 AI 비서 애플리케이션을 개발합니다.', '2025-09-28', '2025-10-03', '2026-01-03', 'IN_PROGRESS', 123, 4, NOW(), NOW()),
(50, '실시간 건강 모니터링 웨어러블 연동 앱', '웨어러블 기기와 연동하여 실시간으로 건강 상태를 모니터링하는 앱입니다.', '2025-09-16', '2025-09-22', '2025-12-22', 'RECRUITING', 298, 6, NOW(), NOW()),
(55, '지속가능한 에너지 관리 스마트 그리드', '재생 에너지를 효율적으로 관리하고 배분하는 스마트 그리드 시스템입니다.', '2025-10-02', '2025-10-08', '2026-02-08', 'RECRUITING', 167, 8, NOW(), NOW()),
(60, 'VR 가상 여행 체험 플랫폼', 'VR 기술을 활용하여 집에서 세계 각지를 여행할 수 있는 체험을 제공합니다.', '2025-09-24', '2025-09-30', '2025-12-30', 'RECRUITING', 456, 5, NOW(), NOW()),
(65, '자율주행차 시뮬레이션 및 테스트 환경', '자율주행 알고리즘을 안전하게 테스트할 수 있는 가상 환경을 구축합니다.', '2025-09-26', '2025-10-02', '2026-01-02', 'RECRUITING', 234, 7, NOW(), NOW()),
(70, '개인화된 뉴스 큐레이션 AI 서비스', '사용자의 관심사와 성향을 분석하여 맞춤형 뉴스를 제공하는 AI 서비스입니다.', '2025-09-19', '2025-09-25', '2025-12-25', 'RECRUITING', 189, 4, NOW(), NOW()),
(75, '온라인 멘토링 매칭 플랫폼', '전문가와 학습자를 연결하는 온라인 멘토링 매칭 플랫폼을 구현합니다.', '2025-10-01', '2025-10-07', '2026-01-07', 'RECRUITING', 345, 6, NOW(), NOW()),
(80, '실시간 재난 알림 및 대피 안내 시스템', '재난 발생 시 실시간으로 알림을 제공하고 최적의 대피 경로를 안내합니다.', '2025-09-21', '2025-09-27', '2025-11-27', 'IN_PROGRESS', 567, 8, NOW(), NOW()),
(85, '크라우드펀딩 기반 스타트업 지원 플랫폼', '혁신적인 아이디어를 가진 스타트업과 투자자를 연결하는 플랫폼입니다.', '2025-09-29', '2025-10-05', '2026-02-05', 'RECRUITING', 234, 5, NOW(), NOW()),
(90, 'AI 기반 개인 영양사 및 식단 관리 앱', '개인의 건강 상태와 선호도를 고려한 맞춤형 식단을 추천하는 AI 앱입니다.', '2025-09-17', '2025-09-23', '2025-12-23', 'RECRUITING', 178, 4, NOW(), NOW()),
(95, '실시간 주차 공간 찾기 및 예약 서비스', '실시간 주차 공간 정보를 제공하고 미리 예약할 수 있는 서비스입니다.', '2025-09-23', '2025-09-29', '2025-12-29', 'RECRUITING', 123, 3, NOW(), NOW()),
(100, '블록체인 기반 투명한 기부 추적 시스템', '기부금의 사용 내역을 투명하게 추적할 수 있는 블록체인 시스템입니다.', '2025-10-03', '2025-10-09', '2026-01-09', 'RECRUITING', 456, 6, NOW(), NOW()),
(2, '음악 AI 작곡 및 편집 도구', 'AI 기술을 활용하여 자동으로 음악을 작곡하고 편집할 수 있는 도구입니다.', '2025-09-27', '2025-10-03', '2026-01-03', 'RECRUITING', 289, 5, NOW(), NOW()),
(5, '스마트 시티 교통 최적화 솔루션', '도시 교통 흐름을 실시간으로 분석하고 최적화하는 스마트 시티 솔루션입니다.', '2025-09-15', '2025-09-21', '2025-12-21', 'RECRUITING', 367, 7, NOW(), NOW()),
(10, '온라인 의료 상담 및 처방 플랫폼', '원격으로 의료진과 상담하고 처방받을 수 있는 온라인 의료 플랫폼입니다.', '2025-10-04', '2025-10-10', '2026-02-10', 'RECRUITING', 234, 8, NOW(), NOW()),
(15, '게임 스트리밍 및 커뮤니티 플랫폼', '게임 스트리밍과 게이머 커뮤니티 기능을 통합한 종합 플랫폼입니다.', '2025-09-18', '2025-09-24', '2025-11-24', 'RECRUITING', 456, 6, NOW(), NOW()),
(20, 'AI 기반 법률 자문 챗봇 서비스', 'AI 기술을 활용하여 법률 질문에 대한 기초적인 자문을 제공하는 챗봇입니다.', '2025-09-25', '2025-10-01', '2026-01-01', 'RECRUITING', 189, 4, NOW(), NOW()),
(25, '실시간 농작물 모니터링 스마트팜', '센서와 AI를 활용하여 농작물의 생육 상태를 실시간으로 모니터링합니다.', '2025-09-20', '2025-09-26', '2025-12-26', 'RECRUITING', 123, 5, NOW(), NOW()),
(30, '가상현실 기반 원격 교육 시스템', 'VR 기술을 활용하여 몰입감 있는 원격 교육 환경을 제공하는 시스템입니다.', '2025-10-06', '2025-10-12', '2026-02-12', 'RECRUITING', 345, 7, NOW(), NOW())

ON CONFLICT (project_id) DO NOTHING;

-- =============================================
-- 좋아요 데이터 삽입 (테스트용)
-- =============================================

-- 사용자 1이 React 관련 프로젝트들을 좋아요한 데이터 추가
INSERT INTO likes (user_id, target_id, target_type, created_at, updated_at) VALUES 
(1, 1, 'PROJECT', NOW(), NOW()),  -- AI 기반 개인 맞춤형 학습 플랫폼 개발
(1, 2, 'PROJECT', NOW() - INTERVAL '7 days', NOW()),  -- 실시간 협업 화이트보드 웹 애플리케이션
(1, 5, 'PROJECT', NOW() - INTERVAL '14 days', NOW()), -- 모바일 AR 쇼핑 경험 애플리케이션
(1, 7, 'PROJECT', NOW() - INTERVAL '21 days', NOW()); -- 클라우드 기반 팀 프로젝트 관리 도구

-- 프로젝트 데이터 확인 쿼리
-- SELECT COUNT(*) as total_projects FROM project_recruitment;
-- SELECT COUNT(*) as total_project_tech_parts FROM project_tech_part;
-- SELECT COUNT(*) as total_project_tech_stacks FROM project_tech_stack;
-- SELECT COUNT(*) as total_likes FROM likes WHERE target_type = 'PROJECT';